### ISSUE TITLE
Errors out with Next.js example

### ISSUE THREAD

**Issue by TxHawks** [johanholmerin/style9-jsx-prop#2]
When I add the plugin and use the css prop, a `style9.create calls should be compiled away` error is thrown.

I made a basic reproduction repo here: https://github.com/TxHawks/style9-next-jsx-prop

**Comment by johanholmerin** [comment]
The style9 next.js plugin runs before all other webpack loaders because it needs to process the code before next.js transforms it. That means it runs before the babel plugins, i.e. before style9-jsx-prop. Since the order needs to be style9-jsx-prop -> style9 -> next.js, the only solution is to add your own babel loader. I added an [example setup](https://github.com/johanholmerin/style9-next-jsx-prop-bug/blob/main/next.config.js) to your example.

I also fixed an issue regarding multiple imports in style9 that caused some issues.

**Comment by TxHawks** [comment]
Thank you!

**Comment by TxHawks** [comment]
Would this also work with Webpack 5 as is or would it need adjustments?

**Comment by johanholmerin** [comment]
Should work

**Comment by TxHawks** [comment]
Sorry to revive an old issue, but the suggested solution throws this on the server:
Webpack 5:
```
HookWebpackError: Cannot read property 'replace' of undefined
    at makeWebpackError (node_modules/next/dist/compiled/webpack/bundle5.js:58378:9)
    at node_modules/next/dist/compiled/webpack/bundle5.js:43243:12
    at eval (eval at create (node_modules/next/dist/compiled/webpack/bundle5.js:31934:10), <anonymous>:12:1)
    at fn (node_modules/next/dist/compiled/webpack/bundle5.js:41175:17)
    at Hook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle5.js:31934:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/next/dist/compiled/webpack/bundle5.js:31736:14)
    at cont (node_modules/next/dist/compiled/webpack/bundle5.js:43240:34)
    at node_modules/next/dist/compiled/webpack/bundle5.js:43286:10
    at node_modules/next/dist/compiled/neo-async/async.js:1:9438
    at done (node_modules/next/dist/compiled/neo-async/async.js:1:9750)
-- inner error --
TypeError: Cannot read property 'replace' of undefined
    at PagesManifestPlugin.createAssets (node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:5:148)
    at node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:7:82
    at fn (node_modules/next/dist/compiled/webpack/bundle5.js:41173:10)
    at Hook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle5.js:31934:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/next/dist/compiled/webpack/bundle5.js:31736:14)
    at cont (node_modules/next/dist/compiled/webpack/bundle5.js:43240:34)
    at node_modules/next/dist/compiled/webpack/bundle5.js:43286:10
    at node_modules/next/dist/compiled/neo-async/async.js:1:9438
    at done (node_modules/next/dist/compiled/neo-async/async.js:1:9750)
    at node_modules/next/dist/compiled/neo-async/async.js:1:9380
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'replace' of undefined
    at PagesManifestPlugin.createAssets (node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:5:148)
    at node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:7:82
    at fn (node_modules/next/dist/compiled/webpack/bundle5.js:41173:10)
    at Hook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle5.js:31934:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/next/dist/compiled/webpack/bundle5.js:31736:14)
    at cont (node_modules/next/dist/compiled/webpack/bundle5.js:43240:34)
    at node_modules/next/dist/compiled/webpack/bundle5.js:43286:10
    at node_modules/next/dist/compiled/neo-async/async.js:1:9438
    at done (node_modules/next/dist/compiled/neo-async/async.js:1:9750)
    at node_modules/next/dist/compiled/neo-async/async.js:1:9380
```

Webpack 4: 
```
TypeError: input.module.originalSource is not a function
    at getNotFoundError (node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:1:625)
    at getModuleBuildError (node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:2479)
    at node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:562
    at Array.map (<anonymous>)
    at node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:476
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:8:17)
    at AsyncSeriesHook.lazyCompileHook (node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
    at node_modules/next/dist/compiled/webpack/bundle4.js:73195:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
TypeError: input.module.originalSource is not a function
    at getNotFoundError (node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:1:625)
    at getModuleBuildError (node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:2479)
    at node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:562
    at Array.map (<anonymous>)
    at node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:476
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:8:17)
    at AsyncSeriesHook.lazyCompileHook (node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
    at node_modules/next/dist/compiled/webpack/bundle4.js:73195:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
TypeError: input.module.originalSource is not a function
    at getNotFoundError (node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:1:625)
    at getModuleBuildError (node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:2479)
    at node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:562
    at Array.map (<anonymous>)
    at node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:476
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:8:17)
    at AsyncSeriesHook.lazyCompileHook (node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
    at node_modules/next/dist/compiled/webpack/bundle4.js:73195:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
TypeError: input.module.originalSource is not a function
    at getNotFoundError (node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:1:625)
    at getModuleBuildError (node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:2479)
    at node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:562
    at Array.map (<anonymous>)
    at node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:476
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:8:17)
    at AsyncSeriesHook.lazyCompileHook (node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
    at node_modules/next/dist/compiled/webpack/bundle4.js:73195:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
```

Any ideas?
